# theme configuration
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# customizations
title: Rhyss Vivian's Blog
description: Thoughts and adventures of a cloud network architect
author: Rhyss Vivian
show_downloads: false
